// <auto-generated />
using System;
using IPTestFormASP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IPTestFormASP.Migrations
{
    [DbContext(typeof(IPTestFormASPDbContext))]
    partial class IPTestFormASPDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("IPTestFormASP.Models.Entities.IPInfos", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("BRABin")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("BRADec")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("IPBin")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("IPDec")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("InputBRABin")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("InputBRADec")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("InputIPBin")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("InputNABin")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("InputNADec")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("InputNetworkClass")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<string>("InputRange")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("InputSMBin")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("InputSMDec")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("InputSubnetBRABin1")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("InputSubnetBRABin2")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("InputSubnetBRABin3")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("InputSubnetBRADec1")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("InputSubnetBRADec2")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("InputSubnetBRADec3")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("InputSubnetNABin1")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("InputSubnetNABin2")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("InputSubnetNABin3")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("InputSubnetNADec1")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("InputSubnetNADec2")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("InputSubnetNADec3")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("InputSubnetRange1")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("InputSubnetRange2")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("InputSubnetRange3")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("InputSubnetSMBin")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("InputSubnetSMDec")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NABin")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NADec")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NetworkClass")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Range")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SMBin")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SMDec")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SchoolClass")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SubnetBRABin1")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SubnetBRABin2")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SubnetBRABin3")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SubnetBRADec1")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SubnetBRADec2")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SubnetBRADec3")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SubnetCount")
                        .HasColumnType("int");

                    b.Property<string>("SubnetNABin1")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SubnetNABin2")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SubnetNABin3")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SubnetNADec1")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SubnetNADec2")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SubnetNADec3")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SubnetRange1")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SubnetRange2")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SubnetRange3")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SubnetSMBin")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SubnetSMDec")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("TurnedInDateTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ID");

                    b.ToTable("IPInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
